//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_TECres
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIO
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public int Tarjeta_Credito { get; set; }
        public Nullable<int> Visitas { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public Nullable<int> ID_Factura { get; set; }
        public int ID_Propiedad { get; set; }
        public int Cedula_Vendedor { get; set; }
        public string Tipo_Anuncio { get; set; }
        public int ID_Publico_Meta { get; set; }
        public Nullable<int> Cedula_Admin { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual VENDEDOR VENDEDOR { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual PROPIEDAD PROPIEDAD { get; set; }
        public virtual TIPO_ANUNCIO TIPO_ANUNCIO1 { get; set; }
    }
}
