//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_TECres
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICO_META
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public int Ingresos { get; set; }
        public int Edad_Min { get; set; }
        public int Edad_Max { get; set; }
        public int ID_Ubicacion { get; set; }
    
        public virtual UBICACION UBICACION { get; set; }
    }
}
